# Build step #1: build the React front end
FROM node:16-alpine AS builder
WORKDIR /frontend
ENV PATH="./node_modules/.bin:$PATH"

COPY ./frontend/package.json ./frontend/package-lock.json ./
COPY ./frontend/src ./
COPY ./frontend/public ./

RUN npm install
RUN npm run build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=builder /frontend/build /usr/share/nginx/html
# COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf

