# Build step #1: build the API
FROM python:3.9.0-alpine
WORKDIR /backend

COPY ./backend/requirements.txt ./
RUN pip install -r ./requirements.txt

EXPOSE 3000
CMD ["gunicorn", "-b", ":8000", "backend.wsgi"]
