# Generated by Django 4.0.6 on 2022-07-16 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('longitude', models.FloatField(verbose_name='Latitude')),
                ('latitude', models.FloatField(verbose_name='Longitude')),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
